apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: "{{ .Values.proxy_image }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - sh
            - -c 
            - |
              /usr/local/bin/proxy \
                --redis "redis://{{- if .Values.redis_password }}:{{ .Values.redis_password }}@{{- end }}{{ .Values.redis_host }}:{{ .Values.redis_port }}"\
                --callback-base-url "http://${POD_IP}:8080"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
