#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"/../

ROOT_DIR="$(pwd)"
source "${ROOT_DIR}/tools/docker/build_and_push_cmds.sh"

IMAGE_REPO=${IMAGE_REPO:-"reyoung/proxy"}
BASE_TAG=${BASE_TAG:-"0.1.0"}
TAG_SUFFIX=${TAG_SUFFIX:-""}

main() {
	local suffix tag root
	if [[ -n "${TAG_SUFFIX}" ]]; then
		suffix="${TAG_SUFFIX}"
	else
		suffix=$(git describe --tags --always --dirty)
		suffix=$(sanitize_tag "${suffix}")
	fi
	tag="${BASE_TAG}-${suffix}"

	root=$(git rev-parse --show-toplevel)

	echo "regenerate protobuf files"
	# Use uv run to make sure pyprotobuf is installed
	cat << EOF | bash 
set -xe
cd pysdk
uv run bash -c 'cd .. && buf generate'
EOF
	echo "Building linux proxy binary with make"
	make -C "${root}/proxy" clean
	make -C "${root}/proxy" linux -j

	echo "Building ${IMAGE_REPO}:${tag}"
	cd proxy
	"${BUILD_CMDS[@]}" -f Dockerfile -t "${IMAGE_REPO}:${tag}" .

	echo "Pushing ${IMAGE_REPO}:${tag}"
	"${PUSH_CMDS[@]}" "${IMAGE_REPO}:${tag}"
}

sanitize_tag() {
	local input=$1
	input=${input//\//-}
	input=${input//[^0-9A-Za-z_.-]/-}
	echo "${input}"
}

main "$@"
