# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: agent_envs/exec/v1/svr.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import agent_envs.exec.v1.svr_pb2


class ProxyBase(abc.ABC):

    @abc.abstractmethod
    async def Exec(self, stream: 'grpclib.server.Stream[agent_envs.exec.v1.svr_pb2.ExecRequest, agent_envs.exec.v1.svr_pb2.ExecResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/agent_envs.exec.v1.Proxy/Exec': grpclib.const.Handler(
                self.Exec,
                grpclib.const.Cardinality.UNARY_UNARY,
                agent_envs.exec.v1.svr_pb2.ExecRequest,
                agent_envs.exec.v1.svr_pb2.ExecResponse,
            ),
        }


class ProxyStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Exec = grpclib.client.UnaryUnaryMethod(
            channel,
            '/agent_envs.exec.v1.Proxy/Exec',
            agent_envs.exec.v1.svr_pb2.ExecRequest,
            agent_envs.exec.v1.svr_pb2.ExecResponse,
        )
